# -*- mode: ruby -*-
# vi: set ft=ruby :

# Ensure a minimum Vagrant version to prevent potential issues.
Vagrant.require_version '>= 1.5.0'

# Configure using Vagrant's version 2 API/syntax.
Vagrant.configure(2) do |config|
  config.vm.box         = 'ubuntu/xenial64'
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # Providers
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.network "private_network", ip: "192.168.49.8"
  config.vm.synced_folder "../", "/home/vagrant/sync"

  # Provision
  config.vm.provision :shell do |sh|
    sh.inline = <<-EOF
      export DEBIAN_FRONTEND=noninteractive;

      # Additional PPAs
      sudo add-apt-repository ppa:fkrull/deadsnakes;
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
      echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list

      # Update
      sudo apt-get update --assume-yes;

      # Install OS dependencies
      sudo apt-get -y --allow-unauthenticated install git make \
          python-dev python-pip python3.4 python3.4-dev python3.6 \
          python3.6-dev postgresql postgresql-contrib python-psycopg2 \
          python3-psycopg2 libpq-dev mongodb-org;

      # Install python build dependencies
      sudo pip install virtualenv tox;
    EOF
  end
end
