# -*- mode: ruby -*-
# vi: set ft=ruby :

# Ensure a minimum Vagrant version to prevent potential issues.
Vagrant.require_version '>= 1.5.0'

# Configure using Vagrant's version 2 API/syntax.
Vagrant.configure(2) do |config|
  config.vm.box         = 'ubuntu/xenial64'
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # Providers
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  # Provision
  config.vm.provision :shell do |sh|
    sh.inline = <<-EOF
      export DEBIAN_FRONTEND=noninteractive;

      # Additional PPAs
      sudo add-apt-repository ppa:fkrull/deadsnakes;
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6;
      echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list;
      sudo add-apt-repository ppa:kelleyk/emacs;

      # Update
      sudo apt-get update --assume-yes;

      # Install OS dependencies
      sudo apt-get -y  --allow-unauthenticated install git make python-dev python-pip python3.4 \
          python3.4-dev postgresql postgresql-contrib python-psycopg2 \
          python3-psycopg2 libpq-dev mongodb-org emacs25;

      # Clone development repositories
      cd /home/ubuntu;
      git clone https://github.com/jk74861372864/.emacs.d.git;
      git clone https://github.com/jk74861372864/sync.git;
      sudo chown -R ubuntu:ubuntu /home/ubuntu/.emacs.d;
      sudo chown -R ubuntu:ubuntu /home/ubuntu/sync;

      # Install python build dependencies
      sudo pip install virtualenv tox;
    EOF
  end
end
